import { DriverTrip, VehicleHealth, DriverProfile, EarningsData, DispatchMessage } from './types';

export const mockCurrentTrip: DriverTrip = {
  id: 'TRIP-84920',
  loadNumber: '#WE6K-78RFE4',
  status: 'NAVIGATING_TO_PICKUP',
  cargoType: 'Pharmaceuticals / Cold Chain Vaccines',
  weight: '34,500 lbs',
  equipment: '53ft Reefer (Continuous -20°C)',
  temperature: '-20°C / -4°F',
  origin: {
    facility: 'Apex BioLogistics Facility #04',
    address: '4200 Logistics Blvd, Dock 14, Los Angeles, CA 90040',
    contact: 'Marcus Vance (Dock Master)',
    phone: '+1 (555) 234-8900',
    dock: 'Bay 14-B (North Gate)',
    appointmentTime: 'Today, 08:30 AM (In 25 mins)',
    instructions: 'Check-in with Guardhouse #2. Present BOL & Hazmat clearance. Engine off while connecting shore power.',
    coordinates: { lat: 34.015, lng: -118.17 },
  },
  destination: {
    consignee: 'Pacific Horizon Medical Center & Distribution',
    address: '8800 Sun Valley Parkway, Phoenix, AZ 85037',
    contact: 'Sarah Jenkins (Receiving Lead)',
    phone: '+1 (555) 987-6543',
    dock: 'Cold Bay 08',
    appointmentTime: 'Today, 02:45 PM',
    instructions: 'Seal verification required before uncoupling. Temperature logger digital download at Bay 08 desk.',
    coordinates: { lat: 33.4484, lng: -112.074 },
  },
  metrics: {
    totalDistanceMi: 372.4,
    remainingDistanceMi: 368.1,
    estimatedHours: '4h 15m',
    eta: '02:45 PM',
    payout: 1420.0,
    speedMph: 62,
    speedLimitMph: 65,
    nextManeuver: {
      instruction: 'Take I-10 East toward San Bernardino / Phoenix',
      distance: '1.4 mi',
      icon: 'turn-right',
    },
  },
  sealNumber: 'SEAL-994821-AZ',
};

export const mockUpcomingLoads: DriverTrip[] = [
  {
    id: 'TRIP-84921',
    loadNumber: '#NX8L-90KLA1',
    status: 'ASSIGNED',
    cargoType: 'High-Tech Electronics & Server Racks',
    weight: '28,000 lbs',
    equipment: '53ft Dry Van (Air Ride)',
    origin: {
      facility: 'Phoenix Sky Harbor Distribution HUB',
      address: '3400 E Sky Harbor Blvd, Phoenix, AZ 85034',
      contact: 'Dave Miller',
      phone: '+1 (555) 345-6789',
      dock: 'Gate 4',
      appointmentTime: 'Tomorrow, 07:00 AM',
      instructions: 'High-value security escort on premises. Dual seal verification.',
      coordinates: { lat: 33.4352, lng: -112.0078 },
    },
    destination: {
      consignee: 'Albuquerque Cloud Data Campus',
      address: '1200 Innovation Way, Albuquerque, NM 87102',
      contact: 'Elena Ramos',
      phone: '+1 (555) 678-1234',
      dock: 'Security Bay 2',
      appointmentTime: 'Tomorrow, 04:30 PM',
      instructions: 'Driver ID badge verification required at outer perimeter.',
      coordinates: { lat: 35.0844, lng: -106.6504 },
    },
    metrics: {
      totalDistanceMi: 420.0,
      remainingDistanceMi: 420.0,
      estimatedHours: '6h 10m',
      eta: 'Tomorrow, 04:30 PM',
      payout: 1680.0,
      speedMph: 0,
      speedLimitMph: 65,
      nextManeuver: {
        instruction: 'Route begins tomorrow morning',
        distance: '0 mi',
        icon: 'straight',
      },
    },
  },
  {
    id: 'TRIP-84922',
    loadNumber: '#RT4P-11MNC9',
    status: 'ASSIGNED',
    cargoType: 'Fresh Organic Produce (Controlled Temp 36°F)',
    weight: '39,200 lbs',
    equipment: '53ft Reefer',
    origin: {
      facility: 'Rio Grande Valley Packing Co.',
      address: '7700 S Valley Rd, El Paso, TX 79901',
      contact: 'Carlos Sanchez',
      phone: '+1 (555) 456-7890',
      dock: 'Dock 21',
      appointmentTime: 'Thu, 06:00 AM',
      instructions: 'Pre-cool trailer to 35°F before entering loading dock.',
      coordinates: { lat: 31.7619, lng: -106.485 },
    },
    destination: {
      consignee: 'Dallas Fresh Direct Hub',
      address: '400 North Stemmons Fwy, Dallas, TX 75207',
      contact: 'Robert Taylor',
      phone: '+1 (555) 789-0123',
      dock: 'Dock 12-A',
      appointmentTime: 'Thu, 06:30 PM',
      instructions: 'Produce inspection team will sample top crates.',
      coordinates: { lat: 32.7767, lng: -96.797 },
    },
    metrics: {
      totalDistanceMi: 635.0,
      remainingDistanceMi: 635.0,
      estimatedHours: '9h 20m',
      eta: 'Thu, 06:30 PM',
      payout: 2350.0,
      speedMph: 0,
      speedLimitMph: 70,
      nextManeuver: {
        instruction: 'Scheduled for Thursday',
        distance: '0 mi',
        icon: 'straight',
      },
    },
  },
];

export const mockCompletedLoads: DriverTrip[] = [
  {
    id: 'TRIP-84918',
    loadNumber: '#CP99-44TYZ1',
    status: 'COMPLETED',
    cargoType: 'Aerospace Composite Parts',
    weight: '19,500 lbs',
    equipment: '53ft Air-Ride Dry Van',
    origin: {
      facility: 'Seattle Aerospace Facility',
      address: '7755 E Marginal Way S, Seattle, WA 98108',
      contact: 'Ken Bradley',
      phone: '+1 (555) 123-4567',
      dock: 'Bay 3',
      appointmentTime: 'Yesterday, 06:00 AM',
      instructions: 'Delivered and confirmed with zero defects.',
      coordinates: { lat: 47.53, lng: -122.31 },
    },
    destination: {
      consignee: 'Portland Assembly Terminal',
      address: '6800 NE Marine Dr, Portland, OR 97218',
      contact: 'Jessica White',
      phone: '+1 (555) 890-1234',
      dock: 'Dock 04',
      appointmentTime: 'Yesterday, 11:30 AM',
      instructions: 'Signed by J. White on POD #9842',
      coordinates: { lat: 45.58, lng: -122.6 },
    },
    metrics: {
      totalDistanceMi: 174.5,
      remainingDistanceMi: 0,
      estimatedHours: '3h 10m',
      eta: 'Delivered',
      payout: 720.0,
      speedMph: 0,
      speedLimitMph: 65,
      nextManeuver: {
        instruction: 'Delivered',
        distance: '0 mi',
        icon: 'straight',
      },
    },
    sealNumber: 'SEAL-77341-WA',
    podSignature: 'J. White (Receiving Lead)',
  },
  {
    id: 'TRIP-84917',
    loadNumber: '#BK12-88QR40',
    status: 'COMPLETED',
    cargoType: 'Industrial Solar Inverters',
    weight: '41,000 lbs',
    equipment: '53ft Flatbed with Tarp',
    origin: {
      facility: 'Reno CleanTech Warehouse',
      address: '1500 USA Pkwy, Sparks, NV 89434',
      contact: 'Tony Starkey',
      phone: '+1 (555) 234-5678',
      dock: 'Flatbed Staging 1',
      appointmentTime: 'Aug 29, 08:00 AM',
      instructions: 'Corner protectors verified and strap tension checked.',
      coordinates: { lat: 39.52, lng: -119.5 },
    },
    destination: {
      consignee: 'Sacramento Grid Infrastructure',
      address: '2200 Powerline Rd, Sacramento, CA 95834',
      contact: 'Danielle Miller',
      phone: '+1 (555) 345-6789',
      dock: 'Unloading Crane 2',
      appointmentTime: 'Aug 29, 01:00 PM',
      instructions: 'Delivered and verified by crane master.',
      coordinates: { lat: 38.65, lng: -121.5 },
    },
    metrics: {
      totalDistanceMi: 138.0,
      remainingDistanceMi: 0,
      estimatedHours: '2h 30m',
      eta: 'Delivered',
      payout: 650.0,
      speedMph: 0,
      speedLimitMph: 65,
      nextManeuver: {
        instruction: 'Delivered',
        distance: '0 mi',
        icon: 'straight',
      },
    },
    sealNumber: 'TARP-SEAL-8831',
    podSignature: 'D. Miller',
  },
];

export const mockVehicleHealth: VehicleHealth = {
  truckNumber: 'TR-001 (Alpha Hauler)',
  model: '2025 Volvo VNL 860 Globetrotter',
  vin: '4V4NC9EH8MN982143',
  fuelPercent: 78,
  rangeMiles: 485,
  odometerMiles: 142850,
  engineStatus: 'Good',
  oilLifePercent: 86,
  batteryVoltage: 14.2,
  defLevelPercent: 82,
  brakePadWearPercent: 24, // 24% worn = 76% life
  nextServiceDue: 'In 7,150 miles (A-Service)',
  reeferTempF: -4,
  reeferTargetF: -4,
  tirePressurePsi: {
    steerLeft: 110,
    steerRight: 110,
    driveLeftOuter: 105,
    driveLeftInner: 106,
    driveRightOuter: 105,
    driveRightInner: 104,
    status: 'Good',
  },
};

export const mockDriverProfile: DriverProfile = {
  id: 'DRV-8829',
  name: 'Steven Vance',
  photoUrl: 'https://images.unsplash.com/photo-1534528741775-53994a69daeb?auto=format&fit=crop&w=300&q=80',
  rating: 4.98,
  completedTrips: 184,
  totalMiles: 58420,
  safetyScore: 99.4,
  onTimeRate: 98.7,
  carrierName: 'Right Direction Logistics / Dropify Fleet',
  assignedTruck: 'TR-001 (Volvo VNL 860)',
  documents: [
    {
      id: 'DOC-CDL-01',
      name: 'Commercial Driver License (CDL Class-A)',
      type: 'License (Endorsements: T, N, H)',
      expiryDate: '2027-08-14',
      daysRemaining: 712,
      status: 'Valid',
      fileUrl: '#',
    },
    {
      id: 'DOC-MED-02',
      name: 'DOT Medical Examiner Certificate (Form MCSA-5876)',
      type: 'Medical Card',
      expiryDate: '2026-11-20',
      daysRemaining: 80,
      status: 'Expiring Soon',
      fileUrl: '#',
    },
    {
      id: 'DOC-GIT-03',
      name: 'Goods In Transit (GIT) $250k Cargo Insurance',
      type: 'Insurance Policy',
      expiryDate: '2027-05-10',
      daysRemaining: 615,
      status: 'Valid',
      fileUrl: '#',
    },
    {
      id: 'DOC-TWIC-04',
      name: 'TWIC Card (Port / Maritime Security Clearance)',
      type: 'Federal Security Badge',
      expiryDate: '2028-03-30',
      daysRemaining: 940,
      status: 'Valid',
      fileUrl: '#',
    },
  ],
};

export const mockEarnings: EarningsData = {
  todayAmount: 585.5,
  breakdown: {
    tripEarnings: 480.0,
    distancePay: 45.5,
    onTimeBonus: 35.0,
    fuelSurcharge: 25.0,
    expensesDeduction: 0.0,
    netEarnings: 585.5,
  },
  weeklyChart: [
    { day: 'Mon', amount: 620, miles: 380 },
    { day: 'Tue', amount: 540, miles: 340 },
    { day: 'Wed', amount: 710, miles: 450 },
    { day: 'Thu', amount: 490, miles: 310 },
    { day: 'Fri', amount: 840, miles: 520 },
    { day: 'Sat', amount: 585, miles: 372 },
    { day: 'Sun', amount: 0, miles: 0 },
  ],
  recentSettlements: [
    {
      id: 'SET-991',
      loadNumber: '#CP99-44TYZ1',
      date: 'Yesterday, 04:30 PM',
      amount: 720.0,
      status: 'Paid',
    },
    {
      id: 'SET-990',
      loadNumber: '#BK12-88QR40',
      date: 'Aug 29, 06:15 PM',
      amount: 650.0,
      status: 'Paid',
    },
    {
      id: 'SET-989',
      loadNumber: '#TR88-21PO99',
      date: 'Aug 28, 05:00 PM',
      amount: 810.0,
      status: 'Paid',
    },
  ],
};

export const mockInitialMessages: DispatchMessage[] = [
  {
    id: 'msg-1',
    sender: 'dispatcher',
    text: 'Morning Steven! Load #WE6K-78RFE4 is confirmed at Apex BioLogistics. Pre-cool reefer to -20°C before entering Gate 2.',
    timestamp: '07:45 AM',
  },
  {
    id: 'msg-2',
    sender: 'driver',
    text: 'Copy that Marcus. Reefer is already humming at -20°C. 15 mins out from the facility.',
    timestamp: '08:05 AM',
    isQuickAction: true,
  },
  {
    id: 'msg-3',
    sender: 'dispatcher',
    text: 'Great work. Dock 14 is prepped and ready for immediate loading upon arrival.',
    timestamp: '08:07 AM',
  },
];
